spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true

app:
  jwt-secret: "do-not-use-in-prod-instead-store-in-secret-store"
  jwt-token-ttl: 3600

---
spring:
  profiles:
    active: jwt